package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
	"testing"

	"github.com/harsh-m-patil/oss-triage-agent/internal/agent"
	opencodeagent "github.com/harsh-m-patil/oss-triage-agent/internal/agent/opencode"
	issuepkg "github.com/harsh-m-patil/oss-triage-agent/internal/issue"
	"github.com/harsh-m-patil/oss-triage-agent/internal/prompt"
	"github.com/harsh-m-patil/oss-triage-agent/internal/sandbox/nosandbox"
)

func TestAgentOutputText_collectsResultEvents(t *testing.T) {
	t.Parallel()

	brief := "## Agent Brief\n\nShip triage."
	got := agentOutputText([]agent.AgentEvent{
		{Kind: agent.EventResult, Result: &agent.Result{Output: brief}},
	})
	if got != brief {
		t.Fatalf("agentOutputText = %q, want %q", got, brief)
	}
}

func TestAgentOutputText_collectsTextEvents(t *testing.T) {
	t.Parallel()

	got := agentOutputText([]agent.AgentEvent{
		{Kind: agent.EventText, Text: "hello"},
	})
	if got != "hello" {
		t.Fatalf("agentOutputText = %q, want hello", got)
	}
}

func TestRunTriageWorkflow_appliesLabelsAndPostsComment(t *testing.T) {
	t.Parallel()

	tracker := &triageIssueTracker{
		issue: issuepkg.Issue{
			Number: 12,
			Title:  "Triage workflow",
			Body:   "Implement automated triage.",
			Labels: []string{"needs-triage"},
		},
	}
	agentProvider := &triageAgent{
		output: "## Agent Brief\n\nShip triage.\n\n```json\n{\"category\":\"enhancement\",\"state\":\"ready-for-agent\",\"close\":false}\n```",
	}

	summary, err := runTriageWorkflow(context.Background(), triageWorkflowDeps{
		Issues:   tracker,
		Sandbox:  nosandbox.NewProvider(),
		RepoRoot: t.TempDir(),
		Agent:    agentProvider,
		Prompt:   prompt.Builder{},
	}, triageOptions{IssueID: "12"})
	if err != nil {
		t.Fatalf("runTriageWorkflow: %v", err)
	}
	if !summary.Success || !summary.Completed {
		t.Fatalf("summary = %+v, want successful completed run", summary)
	}
	if !slices.Equal(tracker.ops, []string{"read", "remove-needs-triage", "add-enhancement", "add-ready-for-agent", "comment"}) {
		t.Fatalf("tracker ops = %v", tracker.ops)
	}
	if len(tracker.comments) != 1 {
		t.Fatalf("comments = %v, want one triage comment", tracker.comments)
	}
	for _, want := range []string{
		"> *This was generated by AI during triage.*",
		"Ship triage.",
	} {
		if !strings.Contains(tracker.comments[0], want) {
			t.Fatalf("comment missing %q:\n%s", want, tracker.comments[0])
		}
	}
	if strings.Count(tracker.comments[0], "## Agent Brief") != 1 {
		t.Fatalf("agent brief duplicated in comment:\n%s", tracker.comments[0])
	}
	if !strings.Contains(agentProvider.prompt, "Implement automated triage.") {
		t.Fatalf("prompt missing issue body:\n%s", agentProvider.prompt)
	}
	if !strings.Contains(agentProvider.prompt, "ready-for-agent") {
		t.Fatalf("prompt missing triage policy:\n%s", agentProvider.prompt)
	}
}

func TestRunTriageWorkflow_rejectsMissingJSONFooter(t *testing.T) {
	t.Parallel()

	tracker := &triageIssueTracker{
		issue: issuepkg.Issue{
			Number: 12,
			Title:  "Triage workflow",
			Body:   "Implement automated triage.",
		},
	}

	_, err := runTriageWorkflow(context.Background(), triageWorkflowDeps{
		Issues:   tracker,
		Sandbox:  nosandbox.NewProvider(),
		RepoRoot: t.TempDir(),
		Agent:    &triageAgent{output: "no structured footer"},
		Prompt:   prompt.Builder{},
	}, triageOptions{IssueID: "12"})
	if err == nil {
		t.Fatal("runTriageWorkflow: want error, got nil")
	}
	if !strings.Contains(err.Error(), "parse triage output") {
		t.Fatalf("err = %v, want parse failure", err)
	}
	if !slices.Equal(tracker.ops, []string{"read"}) {
		t.Fatalf("tracker ops = %v, want no side effects after parse failure", tracker.ops)
	}
}

func TestListTriageCandidates_mergesBucketsOldestFirst(t *testing.T) {
	t.Parallel()

	tracker := &triageIssueTracker{
		listByQuery: map[string][]issuepkg.Issue{
			"label:needs-triage": {
				{Number: 15, Title: "Needs triage"},
			},
			"": {
				{Number: 9, Title: "Untriaged"},
				{Number: 15, Title: "Needs triage", Labels: []string{"needs-triage"}},
				{Number: 20, Title: "Already triaged", Labels: []string{"bug", "ready-for-agent"}},
			},
		},
	}

	got, err := listTriageCandidates(context.Background(), tracker)
	if err != nil {
		t.Fatalf("listTriageCandidates: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("candidates = %+v, want 2", got)
	}
	if got[0].Number != 9 || got[0].Bucket != "unlabeled" {
		t.Fatalf("first candidate = %+v, want unlabeled #9", got[0])
	}
	if got[1].Number != 15 || got[1].Bucket != "needs-triage" {
		t.Fatalf("second candidate = %+v, want needs-triage #15", got[1])
	}
}

type triageIssueTracker struct {
	issue       issuepkg.Issue
	listByQuery map[string][]issuepkg.Issue
	ops         []string
	comments    []string
}

func (t *triageIssueTracker) ReadIssue(_ context.Context, id string) (*issuepkg.Issue, error) {
	if id != "12" && id != fmt.Sprintf("%d", t.issue.Number) {
		return nil, fmt.Errorf("ReadIssue id = %q", id)
	}
	t.ops = append(t.ops, "read")
	iss := t.issue
	return &iss, nil
}

func (t *triageIssueTracker) ListIssues(_ context.Context, query string) ([]issuepkg.Issue, error) {
	if t.listByQuery == nil {
		return nil, fmt.Errorf("unexpected ListIssues query %q", query)
	}
	items, ok := t.listByQuery[query]
	if !ok {
		return nil, fmt.Errorf("unsupported list query %q", query)
	}
	return items, nil
}

func (t *triageIssueTracker) Comment(_ context.Context, id, body string) error {
	t.ops = append(t.ops, "comment")
	t.comments = append(t.comments, body)
	return nil
}

func (t *triageIssueTracker) AddLabel(_ context.Context, _, label string) error {
	t.ops = append(t.ops, "add-"+label)
	return nil
}

func (t *triageIssueTracker) RemoveLabel(_ context.Context, _, label string) error {
	t.ops = append(t.ops, "remove-"+label)
	return nil
}

func (t *triageIssueTracker) Lock(context.Context, string) error {
	return fmt.Errorf("unexpected Lock call")
}

func (t *triageIssueTracker) Unlock(context.Context, string) error {
	return fmt.Errorf("unexpected Unlock call")
}

type triageAgent struct {
	prompt string
	output string
}

func (a *triageAgent) Name() string { return "recording-triage-agent" }

func (a *triageAgent) Env() map[string]string { return nil }

func (a *triageAgent) BuildLaunch(prompt string) agent.Launch {
	a.prompt = prompt
	payload, _ := json.Marshal(map[string]any{
		"type": "text",
		"part": map[string]string{
			"type": "text",
			"text": a.output,
		},
	})
	return agent.Launch{Argv: []string{"printf", "%s\n", string(payload)}}
}

func (a *triageAgent) ParseStreamLine(line string) ([]agent.AgentEvent, error) {
	return opencodeagent.NewProvider("opencode/test", opencodeagent.Options{}).ParseStreamLine(line)
}

var _ issuepkg.IssueTracker = (*triageIssueTracker)(nil)
var _ agent.AgentProvider = (*triageAgent)(nil)
